name: material_speed_dial
description: A speed dial package for Flutter with material design.
version: 0.0.7
homepage: https://github.com/Taskulu/material_speed_dial.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter: